name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-publish:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Clean previous builds
        run: |
          rm -rf dist build *.egg-info || true

      - name: Verify project metadata
        run: |
          python - << 'PY'
          import pathlib, sys
          try:
              import tomllib  # py311+
          except Exception:
              import tomli as tomllib
          data = tomllib.loads(pathlib.Path('pyproject.toml').read_text(encoding='utf-8'))
          name = data.get('project', {}).get('name')
          print('project.name =', name)
          if name != 'lite-slurm':
              print('ERROR: project.name must be "lite-slurm"')
              sys.exit(1)
          PY

      - name: Build package
        run: |
          python -m build
          ls -l dist
          python - << 'PY'
          import os, sys
          files = os.listdir('dist')
          print('dist files:', files)
          if not any(f.startswith('lite_slurm-') and f.endswith('.whl') for f in files):
              print('ERROR: wheel filename must start with lite_slurm-')
              sys.exit(1)
          PY

      - name: Publish to PyPI with OIDC (Trusted Publisher)
        if: ${{ secrets.PYPI_API_TOKEN == '' || secrets.PYPI_API_TOKEN == null }}
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish to PyPI with API token
        if: ${{ secrets.PYPI_API_TOKEN != '' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}